version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.11
    working_directory: /go/src/github.com/exopulse/unit
    steps:
    - checkout
    - run: go get -v -t -d ./...
    - run: go test -coverprofile=/tmp/cover.out -v ./...